# render.yaml
services:
  - type: web
    name: wayne-enterprises
    env: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION
        value: 18
    plan: free
    numInstances: 1
    httpPort: 3000
    healthCheckPath: /