# render.yaml
services:
  - type: web
    name: wayne-enterprises-backend
    env: python
    build:
      dockerfile: backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    numInstances: 1

  - type: web
    name: wayne-enterprises-frontend
    env: node
    build:
      dockerfile: frontend/Dockerfile
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: wayne-enterprises-backend
          type: web
          property: url
    plan: free
    routes:
      - type: rewrite
        source: /
        destination: /index.html